plugins {
    id 'com.barrybecker4.bb4.scala-library' version '2.0-SNAPSHOT'
    id 'com.barrybecker4.bb4.publish' version '2.0-SNAPSHOT'
    id 'com.barrybecker4.bb4.application' version '2.0-SNAPSHOT'
}

description = 'Scala Java2D library and demos (based on code from Java 2D by J. Knudsen)'
group = 'com.barrybecker4'
version = '2.0-SNAPSHOT'

bb4 {
    archivesBaseName.set('bb4-imageproc')
    mainClass.set('com.barrybecker4.java2d.imageproc.FilterSamplerApp')
}

dependencies {
    implementation 'org.slf4j:slf4j-api:2.0.16'
    implementation 'com.barrybecker4:bb4-optimization:2.0-SNAPSHOT'
    implementation 'com.barrybecker4:bb4-ui:2.0-SNAPSHOT'
    implementation 'com.barrybecker4:bb4-common:2.0-SNAPSHOT'
    implementation fileTree(dir: 'lib', include: 'jhlabs-1.0.3.jar')
}

// not everything is included. There are a lot of examples that we do not need in the deployed library jar.
jar {
    include 'com/barrybecker4/java2d/imageproc/**/*.class'
    include 'com/barrybecker4/java2d/ui/**/*.class'
    include 'com/barrybecker4/java2d/*.class'
}

tasks.register('runSpaceInvaders', JavaExec) {
    group = 'application'
    description = 'Runs the Space Invaders demo'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.barrybecker4.java2d.spaceinvaders.SpaceInvadersGame'
}
